package com.jt17.fakestorecompose.core.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

val seed = Color(0xFF706E00)

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

/** Light mode colors **/
val primary_light: Color = Color(0xFF636100)
val onPrimary_light: Color = Color(0xFFFFFFFF)
val primaryContainer_light: Color = Color(0xFFEBE86E)
val onPrimaryContainer_light: Color = Color(0xFF1D1D00)
val secondary_light: Color = Color(0xFF7F5600)
val onSecondary_light: Color = Color(0xFFFFFFFF)
val secondaryContainer_light: Color = Color(0xFFFFDDAE)
val onSecondaryContainer_light: Color = Color(0xFF281800)
val tertiary_light: Color = Color(0xFFA14002)
val onTertiary_light: Color = Color(0xFFFFFFFF)
val tertiaryContainer_light: Color = Color(0xFFFFDBCC)
val onTertiaryContainer_light: Color = Color(0xFF351000)
val error_light: Color = Color(0xFFBA1A1A)
val errorContainer_light: Color = Color(0xFFFFDAD6)
val onError_light: Color = Color(0xFFFFFFFF)
val onErrorContainer_light: Color = Color(0xFF410002)
val background_light: Color = Color(0xFFFFFBFF)
val onBackground_light: Color = Color(0xFF1C1C16)
val surface_light: Color = Color(0xFFFFFBFF)
val onSurface_light: Color = Color(0xFF1C1C16)
val surfaceVariant_light: Color = Color(0xFFE6E3D1)
val onSurfaceVariant_light: Color = Color(0xFF48473A)
val outline_light: Color = Color(0xFF797869)
val inverseOnSurface_light: Color = Color(0xFFF4F0E7)
val inverseSurface_light: Color = Color(0xFF31302B)
val inversePrimary_light: Color = Color(0xFFCECB55)
val shadow_light: Color = Color(0xFF000000)
val surfaceTint_light: Color = Color(0xFF636100)
val outlineVariant_light: Color = Color(0xFFCAC7B6)
val scrim_light: Color = Color(0xFF000000)

/** Dark mode colors **/
val primary_dark: Color = Color(0xFFCECB55)
val onPrimary_dark: Color = Color(0xFF333200)
val primaryContainer_dark: Color = Color(0xFF1B1A00)
val onPrimaryContainer_dark: Color = Color(0xFFEBE86E)
val secondary_dark: Color = Color(0xFFFCBB4A)
val onSecondary_dark: Color = Color(0xFF432C00)
val secondaryContainer_dark: Color = Color(0xFF604100)
val onSecondaryContainer_dark: Color = Color(0xFFFFDDAE)
val tertiary_dark: Color = Color(0xFFFFB695)
val onTertiary_dark: Color = Color(0xFF571F00)
val tertiaryContainer_dark: Color = Color(0xFF7B2F00)
val onTertiaryContainer_dark: Color = Color(0xFFFFDBCC)
val error_dark: Color = Color(0xFFFFB4AB)
val errorContainer_dark: Color = Color(0xFF93000A)
val onError_dark: Color = Color(0xFF690005)
val onErrorContainer_dark: Color = Color(0xFFFFDAD6)
val background_dark: Color = Color(0xFF1C1C16)
val onBackground_dark: Color = Color(0xFFE6E2D9)
val surface_dark: Color = Color(0xFF1C1C16)
val onSurface_dark: Color = Color(0xFFE6E2D9)
val surfaceVariant_dark: Color = Color(0xFF48473A)
val onSurfaceVariant_dark: Color = Color(0xFFCAC7B6)
val outline_dark: Color = Color(0xFF939181)
val inverseOnSurface_dark: Color = Color(0xFF1C1C16)
val inverseSurface_dark: Color = Color(0xFFE6E2D9)
val inversePrimary_dark: Color = Color(0xFF636100)
val shadow_dark: Color = Color(0xFF000000)
val surfaceTint_dark: Color = Color(0xFFCECB55)
val outlineVariant_dark: Color = Color(0xFF48473A)
val scrim_dark: Color = Color(0xFF000000)